POST http://localhost:3000/api/user/register HTTP/1.1
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "johndoe@example.com",
    "username": "johndoe",
    "password": "johndoePass",
    "repeatPassword": "johndoePass"
}

###
POST http://localhost:3000/api/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password": "johndoePass"
}

###

