###
# Get all books with no sorting pramaters
GET http://{{host}}/api/books HTTP/1.1
Content-Type: application/json

###
# Get all books with sorting pramaters
GET http://{{host}}/api/books?sortBooks=true&sortBy=price&sortDirection=desc&pageSize=2&currPage=0 HTTP/1.1
Content-Type: application/json

###
# Send request that creates a new book
POST http://{{host}}/api/books HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{adminToken}}
# Authorization: Bearer {{userToken}}

{
	"title": "The Hobbit",
	"author": "J.R.R. Tolkien",
	"isbn": "9780547928267",
	"description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod, vero doloribus dolore sequi temporibus optio sed soluta debitis laudantium perferendis! Voluptate ipsam saepe quisquam. Dolores ex assumenda dolorem exercitationem deleniti.",
	"pages": 320,
	"price": 29.99,
	"currency": "USD",
	"qty": 10,
	"sales": 0,
	"likes": 0,
	"comments": 0
}

###
# Get book data with comments sorted using default settings
GET http://{{host}}/api/books/9780547928226 HTTP/1.1
Content-Type: application/json

###
# Get book data with sorted comments by creation time in descending order
GET http://{{host}}/api/books/9780547928227?sortComments=true&sortBy=createdAt&sortDirection=desc HTTP/1.1
Content-Type: application/json

###
# Updates a book information
PATCH http://{{host}}/api/books/978054792822 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{adminToken}}
# Authorization: Bearer {{userToken}}

{
	"title": "The Hobbit",
	"author": "J.R.R. Tolkien",
	"isbn": "978054792822",
	"description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod, vero doloribus dolore sequi temporibus optio sed soluta debitis laudantium perferendis! Voluptate ipsam saepe quisquam. Dolores ex assumenda dolorem exercitationem deleniti.",
	"pages": 620,
	"price": 29.99,
	"currency": "USD",
	"qty": 10,
	"sales": 0,
	"likes": 0,
	"comments": 0
}


###
# Delete a book
DELETE http://{{host}}/api/books/978054792822 HTTP/1.1
# DELETE http://{{host}}/api/books/9780547928210 HTTP/1.1
Authorization: Bearer {{adminToken}}
# Authorization: Bearer {{userToken}}

###
# Create comment for a book
POST http://{{host}}/api/books/978054792823/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "commentText": "Comment 9855984"
}

###
# Get a comments for a book
GET http://{{host}}/api/books/978054792823/comments HTTP/1.1
Content-Type: application/json

###
# Delete a comment for a book
DELETE http://{{host}}/api/books/978054792823/comment/JjSsbwiJZIDS3JKE15Cx3 HTTP/1.1
Authorization: Bearer {{adminToken}}

###
# Like a book
POST http://{{host}}/api/books/978054792823/likes HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{userToken}}

###
# Get likes for a book - TODO
GET http://{{host}}/api/books/978054792823/likes HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{userToken}}

###
# Dislike a book
DELETE http://{{host}}/api/books/978054792823/likes HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{userToken}}
