POST http://{{host}}/api/user/register HTTP/1.1
Content-Type: application/json

{
    "firstname": "{{registerFirstName}}",
    "lastname": "{{registerLastName}}",
    "email": "{{registerEmail}}",
    "username": "{{registerUsername}}",
    "password": "{{registerPassword}}",
    "repeatPassword": "{{registerRepeatPassword}}"
}

###
POST http://{{host}}/api/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "{{loginEmail}}",
    "password": "{{loginPassword}}"
}

###
GET http://{{host}}/api/user/johndoe HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
 
###
POST http://{{host}}/api/user/johndoe HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Unufri"
}